FROM nvcr.io/nvidia/dgl:24.04-py3

# RUN apt-get -y update && apt-get -y install git

# RUN pip install --upgrade pip

# RUN pip install --pre torch torchvision torchaudio

# RUN pip install --pre dgl -f https://data.dgl.ai/wheels/torch-2.3/cu121/repo.html

# RUN pip install dglgo -f https://data.dgl.ai/wheels-test/repo.html

# RUN pip install "pandas<2.0.0"

# RUN pip uninstall -y numpy && pip install numpy